In [2]:
import pandas as pd

1. Create a nested list which contains the name, age and race of 10 people each. Turn this list to a dataframe.

In [3]:
bio = [['Anita', 18, 'African'], ['David', 25, 'Australian'],  ['Chioma', 10, 'African'],
       ['Jwon', 22, 'Asian'], ['Adele', 30, 'European'], ['Aoife', 18, 'White Irish'], 
       ['Harvey', 35, 'American'], ['Shannon', 28, 'Irish'], ['Mark', 45, 'Native American'], ['Jay', 26, 'Central American']]
                                                                                  
df = pd.DataFrame(bio)
print(df)

print("\n Shape of the data: ", df.shape)

         0   1                 2
0    Anita  18           African
1    David  25        Australian
2   Chioma  10           African
3     Jwon  22             Asian
4    Adele  30          European
5    Aoife  18       White Irish
6   Harvey  35          American
7  Shannon  28             Irish
8     Mark  45   Native American
9      Jay  26  Central American

 Shape of the data:  (10, 3)


2. Label the columns with the appropriate column names

In [4]:
df = pd.DataFrame (bio, columns = ['Name', 'Age', 'Race'])
print (df)

      Name  Age              Race
0    Anita   18           African
1    David   25        Australian
2   Chioma   10           African
3     Jwon   22             Asian
4    Adele   30          European
5    Aoife   18       White Irish
6   Harvey   35          American
7  Shannon   28             Irish
8     Mark   45   Native American
9      Jay   26  Central American


3. Add a new column to your dataframe called weight and enter values for it.

In [5]:
df.insert(3, "Weight", [55, 70, 34, 81, 74, 55, 62, 90, 72, 75], True)
df

Name  Age              Race  Weight
0    Anita   18           African      55
1    David   25        Australian      70
2   Chioma   10           African      34
3     Jwon   22             Asian      81
4    Adele   30          European      74
5    Aoife   18       White Irish      55
6   Harvey   35          American      62
7  Shannon   28             Irish      90
8     Mark   45   Native American      72
9      Jay   26  Central American      75

4. Change the name of the column for "weight" to "height". Feel free to use any method you find. 

In [6]:
df.rename(columns={'Weight': 'Height'}, inplace=True)
print(df)

      Name  Age              Race  Height
0    Anita   18           African      55
1    David   25        Australian      70
2   Chioma   10           African      34
3     Jwon   22             Asian      81
4    Adele   30          European      74
5    Aoife   18       White Irish      55
6   Harvey   35          American      62
7  Shannon   28             Irish      90
8     Mark   45   Native American      72
9      Jay   26  Central American      75


5. Change the row index to another indexing of your choice.

In [10]:
df.index = ['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10']

print(df)

        Name  Age              Race  Height
C1     Anita   18           African      55
C2     David   25        Australian      70
C3    Chioma   10           African      34
C4      Jwon   22             Asian      81
C5     Adele   30          European      74
C6     Aoife   18       White Irish      55
C7    Harvey   35          American      62
C8   Shannon   28             Irish      90
C9      Mark   45   Native American      72
C10      Jay   26  Central American      75


In [28]:
#copying out the array to give it a new variable so that the original array is not changed
df1 = df[0:10].copy()
df1.x = -1
print(df1)

        Name  Age              Race  Height
C1     Anita   18           African      55
C2     David   25        Australian      70
C3    Chioma   10           African      34
C4      Jwon   22             Asian      81
C5     Adele   30          European      74
C6     Aoife   18       White Irish      55
C7    Harvey   35          American      62
C8   Shannon   28             Irish      90
C9      Mark   45   Native American      72
C10      Jay   26  Central American      75


6. Select/display only the age and race columns

In [32]:
df1[['Age', 'Race']]


Age              Race
C1    18           African
C2    25        Australian
C3    10           African
C4    22             Asian
C5    30          European
C6    18       White Irish
C7    35          American
C8    28             Irish
C9    45   Native American
C10   26  Central American

7. Select/display the first five names and their age 

In [33]:
df1.loc['C1': 'C5']

Name  Age        Race  Height
C1   Anita   18     African      55
C2   David   25  Australian      70
C3  Chioma   10     African      34
C4    Jwon   22       Asian      81
C5   Adele   30    European      74

8. Select all rows but only the third column

In [35]:
df1.loc[:, 'Height']

C1     55
C2     70
C3     34
C4     81
C5     74
C6     55
C7     62
C8     90
C9     72
C10    75
Name: Height, dtype: int64

9. Write some code to return the row index back to the default numbering before it was changed. Use your researching skills.

In [39]:
df.reset_index(level=None, drop=True, inplace=True)
print(df)

      Name  Age              Race  Height
0    Anita   18           African      55
1    David   25        Australian      70
2   Chioma   10           African      34
3     Jwon   22             Asian      81
4    Adele   30          European      74
5    Aoife   18       White Irish      55
6   Harvey   35          American      62
7  Shannon   28             Irish      90
8     Mark   45   Native American      72
9      Jay   26  Central American      75


In [40]:
chimamanda = {"Books":["Americanah", "Half of a Yellow Sun", "Purple Hibiscus",
                    "The Thing Around Your Neck", "We Should All Be Feminists"], 
             "Ratings":[297972, 120131, 5116, 32064, 204882]}

10. Create a dataframe from the dictionary above. Using the dataframe, select books with ratings not less than 200000

In [41]:
chimamandaBooks = pd.DataFrame(chimamanda)
chimamandaBooks

Books  Ratings
0                  Americanah   297972
1        Half of a Yellow Sun   120131
2             Purple Hibiscus     5116
3  The Thing Around Your Neck    32064
4  We Should All Be Feminists   204882

In [48]:
chimamandaBooks_ = chimamandaBooks.loc[chimamandaBooks['Ratings'] > 200000]
chimamandaBooks_

Books  Ratings
0                  Americanah   297972
4  We Should All Be Feminists   204882

In [8]:
import numpy as np

11. Create a numpy array with data type boolean

In [9]:
bool_arr = np.array([1, 0.5, 0, None, 'a', '', True, False], dtype=bool)
print(bool_arr)

[ True  True False False  True False  True False]


In [23]:
# 12. Convert the following array to an integer

a = np.array([[True, False, False],
              [True, True, True],
              [False, False, False]])

p = a.astype(int)

print(p)

[[1 0 0]
 [1 1 1]
 [0 0 0]]


In [11]:
#13. Stack these numpy arrays - vertically and horizontally

a = np.array([[7, 8, 9],
              [10, 11, 12]])

aa = np.array([[1, 2, 3],
               [4, 5, 6]])

In [12]:
#stacking vertically = stacking by column and you can stack these arrays using the vstack

aaa = np.vstack((a, aa))
print(aaa)

[[ 7  8  9]
 [10 11 12]
 [ 1  2  3]
 [ 4  5  6]]


In [13]:
#stacking horizontally = stacking by row and you can stack these arrays using the hstack

aaa = np.hstack((a,aa))
print(aaa)

[[ 7  8  9  1  2  3]
 [10 11 12  4  5  6]]


14. Create 2 3D arrays, add them together to create a new array, then sort the new array.

In [14]:
mark = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
mark_ = np.array([[[15, 13, 14], [18, 17, 16]], [[19, 20, 21], [24, 22, 23]]])

mark1 = np.add(mark, mark_)

print(mark1)

[[[16 15 17]
  [22 22 22]]

 [[26 28 30]
  [34 33 35]]]


In [15]:
print(np.sort(mark1))

[[[15 16 17]
  [22 22 22]]

 [[26 28 30]
  [33 34 35]]]


In [16]:
#15. Using step slicing, slice the array below from any position using 3 steps

a = np.array([5, 8, 7, 1, 0, 9, 4, 2, 6, 3])


In [17]:
print(a[0:7:3])   #a = (start:end:step)

[5 1 4]
